set-option -g history-limit 100000
set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:Tc"
bind-key f run-shell "tmux neww ~/tmux-sessionizer"
set -g extended-keys on
set -g extended-keys-format csi-u
