- hosts: localhost
  vars:
    home: "{{ lookup('env', 'HOME') }}"
    devenv_dir: "{{ playbook_dir }}"
    zsh_custom: "{{ lookup('env', 'ZSH_CUSTOM') | default(lookup('env', 'HOME') + '/.oh-my-zsh/custom', true) }}"

  tasks:
    # ─── Dotfile symlinks ─────────────────────────────────────────────────────

    - name: Remove dotfile symlinks
      file:
        path: "{{ home }}/{{ item }}"
        state: absent
      loop:
        - .zshrc
        - .p10k.zsh
        - .tmux.conf
        - tmux-sessionizer

    - name: Remove Neovim config symlink
      file:
        path: "{{ home }}/.config/nvim"
        state: absent

    - name: Remove go-code envrc symlink
      file:
        path: "{{ home }}/go-code/.envrc.local"
        state: absent

    # ─── Zsh plugins/theme ────────────────────────────────────────────────────

    - name: Remove Powerlevel10k theme
      file:
        path: "{{ zsh_custom }}/themes/powerlevel10k"
        state: absent

    - name: Remove zsh-autosuggestions plugin
      file:
        path: "{{ home }}/.oh-my-zsh/plugins/zsh-autosuggestions"
        state: absent

    # ─── Oh My Zsh ────────────────────────────────────────────────────────────

    - name: Remove Oh My Zsh
      file:
        path: "{{ home }}/.oh-my-zsh"
        state: absent
