#!/usr/bin/env bash

session=$(find ~ /mnt/c/Users/magayev/Documents/go/src /mnt/c/Users/magayev/Documents/python /mnt/c/Users/magayev/Documents/simbrella/src /mnt/c/Users/magayev/Downloads /mnt/c/Users/magayev/Documents/src -mindepth 1 -maxdepth 1 -type d | fzf)
session_name=$(basename "$session" | tr . _)

if ! tmux hash-session -t "$session_name" 2>/dev/null;  then
   tmux new-session -s "$session_name" -c "$session" -d
fi

tmux switch-client -t "$session_name"
